- id: bed_lamp_dusk_on
  alias: Dusk on
  trigger:
  - event: sunset
    offset: +00:15:00
    platform: sun
  action:
  - entity_id: switch.derek_bedroom_lamp
    service: switch.turn_on
  initial_state: true
- id: '1532278514912'
  alias: Sleep Cool
  trigger:
  - at: '21:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.home_empty
    state: 'false'
  - above: '70'
    condition: numeric_state
    entity_id: sensor.cottage_temperature
  action:
  - service: script.bedtime_ac
  - data:
      message: The bedroom AC has been turned on
    service: notify.general
- id: '1535646752999'
  alias: Temperatures Equal
  trigger:
  - platform: template
    value_template: '{% if states("sensor.cottage_temperature") | int == states("sensor.netatmo_outdoor_temperature_2")
      | int %}true{% endif %}'
  condition: []
  action:
    service: notify.general
    data_template:
      message: Indoor and outdoor temperatures have equalized at {{ states("sensor.netatmo_outdoor_temperature_2")
        }} degrees. Inside the humidity is {{ states("sensor.netatmo_indoor_humidity_2")
        }}%. Outdoor humidity is {{ states("sensor.netatmo_outdoor_temperature_2")
        }}%.
- id: '1535836945192'
  alias: Back Porch On
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: sensor.home_empty
    state: 'false'
  action:
  - data:
      entity_id: switch.ge_12720_outdoor_smart_switch_switch
    service: switch.turn_on
  - data:
      message: Back porch turned on.
    service: notify.general
- id: '1535837544489'
  alias: Back Porch Off
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.ge_12720_outdoor_smart_switch_switch
    service: switch.turn_off
  - data:
      message: Back porch turned off.
    service: notify.general
