- id: '1532278514912'
  alias: Sleep Cool
  trigger:
  - at: '21:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.unoccupied_mode
    state: "off"
  - above: '75'
    condition: numeric_state
    entity_id: sensor.dark_sky_daytime_high_temperature
  action:
  - service: script.bedtime_ac
- id: '1535646752999'
  alias: Temperatures Equal
  trigger:
  - platform: template
    value_template: '{% if states("sensor.cottage_temperature") | int == states("sensor.netatmo_outdoor_temperature_2")
      | int %}true{% endif %}'
  condition: []
  action:
  - data_template:
      message: Indoor and outdoor temperatures have equalized at {{ states("sensor.netatmo_outdoor_temperature_2")
        }} degrees. Inside the humidity is {{ states("sensor.netatmo_indoor_humidity_2")
        }}%. Outdoor humidity is {{ states("sensor.netatmo_outdoor_humidity_2") }}%.
    service: notify.general
  - delay: 02:30:00
- id: '1535836945192'
  alias: Pre-Dusk Tasks
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  condition:
  - condition: state
    entity_id: sensor.unoccupied_mode
    state: "off"
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.ge_12720_outdoor_smart_switch_switch
  - service: switch.turn_on
    data:
      entity_id: switch.derek_bedroom_lamp
- id: '1535837544489'
  alias: Back Porch Off
  trigger:
  - at: '21:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.ge_12720_outdoor_smart_switch_switch
    service: switch.turn_off
- id: '1535920489195'
  alias: Away Morning
  trigger:
  - event: sunrise
    offset: -00:10:00
    platform: sun
  condition:
  - condition: state
    entity_id: sensor.unoccupied_mode
    state: "on"
  action:
  - data:
      data:
        brightness: 20
      entity_id: light.living_room_lamp
    service: light.turn_on
  - data:
      data:
        brightness: 100
      entity_id: light.the_sink_hole
    service: light.turn_on
- id: '1535920745991'
  alias: Away Evening
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition:
  - condition: state
    entity_id: sensor.unoccupied_mode
    state: "on"
  action:
  - data:
      data:
        brightness: 100
      entity_id: light.living_room_lamp
    service: light.turn_on
  - data:
      entitiy_id: switch.derek_bedroom_lamp
    service: switch.turn_on
- id: '1535921022697'
  alias: Away Night
  trigger:
  - at: '21:46'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.unoccupied_mode
    state: "on"
  action:
  - data:
      entity_id: light.living_room_lamp
    service: light.turn_off
  - data:
      data:
        brightness: 2
      entity_id: light.the_sink_hole
    service: light.turn_on
  - delay: 22 minutes
  - data:
      entitiy_id: switch.derek_bedroom_lamp
    service: switch.turn_off
- id: 'weather_alert_doooooom'
  alias: NWS Notification Weather Alert
  trigger:
    platform: state
    entity_id: sensor.nws_alert_count
  condition:
    condition: template
    value_template: '{{states.sensor.nws_alert_count.state | int > 0}}'
  action:
  - data_template:
      message: There has been a change in the weather alert status for our area.
      
        {{ state_attr('sensor.nws_alert_event', 'features')[0].properties.headline }}
        {{ state_attr('sensor.nws_alert_event', 'features')[0].properties.description }}
    service: notify.general