# Living Room Lamp
- platform: tplink
  host: 192.168.131.95
#S inkhole
- platform: tplink
  host: 192.168.131.90
# Living Room Lamp Middle
- platform: tplink
  host: 192.168.131.91
# Dining Room 1
- platform: tplink
  host: 192.168.131.92
# Dining Room 2
- platform: tplink
  host: 192.168.131.99
# Dining Room 3
- platform: tplink
  host: 192.168.131.100
# Dining Room 4
- platform: tplink
  host: 192.168.131.101