resources:
  - url: /local/entity-attributes-card.js?v=2
    type: js
  - url: /local/slider-entity-row.js
    type: js

title: Yggdrasil

views:
    # Home Tab
  - id: home
    icon: mdi:home-assistant
    cards: !include lovelace_views/home.yaml
  - id: media
    icon: mdi:youtube-tv
    cards: !include lovelace_views/media.yaml
  - id: climate
    icon: mdi:weather-partlycloudy
    cards: !include lovelace_views/climate.yaml
  - id: indoors
    icon: mdi:thermostat
    cards: !include lovelace_views/indoors.yaml
  - id: cameras
    icon: mdi:cctv
    cards: !include lovelace_views/cameras.yaml
  - id: network
    icon: mdi:nas
    cards: !include lovelace_views/network.yaml
  - id: settings
    icon: mdi:settings-outline
    cards: !include lovelace_views/settings.yaml
    badges:
      - sensor.unoccupied_mode
      - sensor.nws_alert_count
  - id: documentation
    icon: mdi:file-document
    cards: !include lovelace_views/documentation.yaml