title: Yggdrasil

views:
    # Home Tab
  - id: home
    icon: mdi:home-assistant
  - id: climate
    icon: mdi:weather-partlycloudy
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - sun.sun
              - sensor.dark_sky_daily_summary
              - sensor.dark_sky_icon  
              - sensor.dark_sky_humidity
              - sensor.dark_sky_pressure
              - sensor.dark_sky_temperature
              - sensor.dark_sky_visibility
              - sensor.dark_sky_wind_bearing
              - sensor.dark_sky_wind_speed
              - sensor.dark_sky_daytime_high_temperature_1
              - sensor.dark_sky_daytime_high_temperature_2
              - sensor.dark_sky_daytime_high_temperature_3
              - sensor.dark_sky_daytime_high_temperature_4
              - sensor.dark_sky_daytime_high_temperature_5
              - sensor.dark_sky_overnight_low_temperature
              - sensor.dark_sky_overnight_low_temperature_1
              - sensor.dark_sky_overnight_low_temperature_2
              - sensor.dark_sky_overnight_low_temperature_3
              - sensor.dark_sky_overnight_low_temperature_4
              - sensor.dark_sky_icon_1
              - sensor.dark_sky_icon_2
              - sensor.dark_sky_icon_3
              - sensor.dark_sky_icon_4
              - sensor.dark_sky_icon_5
  - id: documentation
    icon: mdi:file-document
    cards: !include lovelace_cards/view_documentation.yaml
  - id: cameras
    icon: mdi:cctv
  - id: media
    icon: mdi:youtube-tv