title: Yggdrasil

views:
    # Home Tab
  - id: home
    icon: mdi:home-assistant
  - id: climate
    icon: mdi:weather-partlycloudy
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: horizontal-stack
            cards:
              - type: iframe
                url: https://embed.windy.com/embed2.html?lat=44.410&lon=-122.701&zoom=8&level=surface&overlay=rain&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=44.187&detailLon=-122.964&metricWind=mph&metricTemp=default&radarRange=-1
                aspect_ratio: 50%
              - type: entities
                entities:
                  - sensor.netatmo_outdoor_temperature
                  - sensor.netatmo_outdoor_humidity
                  - sensor.netatmo_indoor_temperature
                  - sensor.netatmo_indoor_humidity
                  - sensor.netatmo_indoor_co2
                  - sensor.netatmo_indoor_noise
                  - sensor.cottage_temperature
                  - sensor.cottage_humidity
                  - sensor.dark_sky_cloud_coverage
                  - sensor.dark_sky_wind_speed
                  - sensor.dark_sky_visibility
                  - sun.sun
              - type: entities
                entities:
                  - sensor.allergy_average_forecasted
                  - sensor.allergy_average_historical
                  - sensor.allergy_index_today
                  - sensor.allergy_index_tomorrow
                  - sensor.allergy_index_yesterday
                  - sensor.disease_average_forecasted
  - id: documentation
    icon: mdi:file-document
    cards: !include lovelace_cards/view_documentation.yaml
  - id: cameras
    icon: mdi:cctv
  - id: media
    icon: mdi:youtube-tv