resources:
  - url: /local/entity-attributes-card.js?v=2
    type: js
  - url: /local/button-card.js
    type: module

title: Yggdrasil

views:
    # Home Tab
  - id: home
    icon: mdi:home-assistant
    cards: !include lovelace_cards/view_home.yaml
  - id: climate
    icon: mdi:weather-partlycloudy
    panel: true
    cards: !include lovelace_cards/view_climate.yaml
  - id: indoors
    icon: mdi:thermostat
    cards: !include lovelace_cards/view_indoor-climate.yaml
  - id: cameras
    icon: mdi:cctv
    cards: !include lovelace_cards/view_camera.yaml
  - id: network
    icon: mdi:nas
    cards: !include lovelace_cards/view_network.yaml
  - id: media
    icon: mdi:youtube-tv
    cards: !include lovelace_cards/view_media.yaml
  - id: documentation
    icon: mdi:file-document
    cards: !include lovelace_cards/view_documentation.yaml