- id: settings
  title: Settings
  icon: mdi:settings
  path: settings
  badges:
    - sun.sun
    - sensor.unoccupied_mode
    - sensor.nws_alert_count
    - sensor.garage_smoke_detector_status
  cards:
    - id: location-stack
      type: vertical-stack
      cards:
      - type: entities
        title: Where Are We
        show_header_toggle: false
        entities:
        - entity: device_tracker.tile_a8b3ea596f9b44fd
          name: Derek
          icon: mdi:owl
        - entity: device_tracker.tile_4c66b3d3606d440e
          name: Bonnie
          icon: mdi:elephant
      - type: entities
        show_header_toggle: false
        entities:
        - entity: sensor.home_to_idx
          name: Home to IDX
          icon: mdi:briefcase
        - entity: sensor.home_to_bend
          name: Home to Bend
          icon: mdi:car
        - entity: sensor.home_to_florence
          name: Home to Florence
          icon: mdi:anchor
        - entity: sensor.home_to_portland
          name: Home to Portland
          icon: mdi:emoticon-poop
        - entity: sensor.home_to_lincoln_city
          name: Home to Portland
          icon: mdi:beach
    - id: ui_and_automation
      type: entities
      title: UI and Automation Controls
      show_header_toggle: false
      entities:
        - entity: input_boolean.fan_out
        - entity: input_select.occupation_override
    - id: bedroom
      type: entities
      title: Bedroom
      show_header_toggle: false
      entities:
        - entity: input_number.bedroom_ac_trigger_temp