- id: location-stack
  type: vertical-stack
  cards:
  - type: entities
    title: Where Are We
    show_header_toggle: false
    entities:
    - entity: device_tracker.tile_a8b3ea596f9b44fd
      name: Derek
      icon: mdi:owl
    - entity: device_tracker.tile_4c66b3d3606d440e
      name: Bonnie
      icon: mdi:elephant
  - type: entities
    show_header_toggle: false
    entities:
    - entity: sensor.home_to_idx
      name: Home to IDX
      icon: mdi:briefcase
    - entity: sensor.home_to_bend
      name: Home to Bend
      icon: mdi:car
    - entity: sensor.home_to_florence
      name: Home to Florence
      icon: mdi:anchor
    - entity: sensor.home_to_portland
      name: Home to Portland
      icon: mdi:emoticon-poop
    - entity: sensor.home_to_lincoln_city
      name: Home to Portland
      icon: mdi:beach
  - type: entities
    title: Transport
    show_header_toggle: false
    entities:
    - entity: sensor.lyft_time
      name: Lyft Pickup Time
    - entity: sensor.lyft_xl_time
      name: Lyft XL Pickup Time
    - type: divider
    - entity: sensor.uberx_time
      name: Uber X Pickup Time
      icon: mdi:uber
    - entity: sensor.uberxl_time
      name: Uber XL Pickup Time
      icon: mdi:uber
- id: ui_and_automation
  type: entities
  title: UI and Automation Controls
  show_header_toggle: false
  entities:
    - entity: input_boolean.fan_out
    - entity: input_boolean.force_away_mode
- id: grouped-automation-controls
  type: vertical-stack
  cards:
    - type: entities
      title: General/Global Automations
      show_header_toggle: false
      entities:
      - entity: automation.back_porch_off
        name: Back Porch Auto-Off
      - entity: automation.work_heater_on
        name: Work Heater Warning
    - type: entities
      title: Occupied Automations
      show_header_toggle: false
      entities:
      - entity: automation.sleep_cool
        name: Hot Bedroom / Ready For Bed
      - entity: automation.pre_dusk_tasks
        name: Pre-Dusk Lights Auto-On
    - type: entities
      title: Unoccupied Automations
      show_header_toggle: false
      entities:
        - entity: automation.unoccupied_morning
          name: Away Morning Lights
        - entity: automation.unoccupied_afternoon
          name: Away Afternoon Lights
        - entity: automation.unoccupied_evening
          name: Away Evening Lights
        - entity: automation.unoccupied_night
          name: Away Night Lights
    - type: entities
      title: Notification Automations
      show_header_toggle: false
      entities:
      - entity: automation.temperatures_equal
        name: Equal Temp. Notification
      - entity: automation.nws_notification_weather_alert
        name: National Weather Service Alerts
