- id: ui_and_automation
  type: entities
  title: UI and Automation Controls
  show_header_toggle: false
  entities:
    - entity: input_boolean.fan_out
    - entity: input_boolean.force_away_mode
- id: grouped-automation-controls
  type: vertical-stack
  cards:
    - type: entities
      title: General Automations
      show_header_toggle: false
      entities:
        - entity: automation.temperatures_equal
          name: Equal Temp. Notification
        - entity: automation.nws_notification_weather_alert
          name: National Weather Service Alerts
        - entity: automation.work_heater_on
          name: Work heater warning
        - entity: automation.let_s_encrypt_renewal
          name: Let's Encrypt Auto-Renewal
    - type: entities
      title: Occupied Automations
      show_header_toggle: false
      entities:
        - entity: automation.pre_dusk_tasks
          name: Pre-Dusk Lights Auto-On
        - entity: automation.back_porch_off
          name: Back Porch Auto-Off
        - entity: automation.sleep_cool
          name: Bedroom AC Cool
    - type: entities
      title: Unoccupied Automations
      show_header_toggle: false
      entities:
        - entity: automation.unoccupied_morning
          name: Away Morning Lights
        - entity: automation.unoccupied_evening
          name: Away Evening Lights
        - entity: automation.unoccupied_night
          name: Away Night Lights
- id: location-stack
  type: vertical-stack
  cards:
    - type: entities
      title: Where Are We
      show_header_toggle: false
      entities:
        - device_tracker.tile_78bc53da2fdc0a07
        - device_tracker.tile_6ddd67e2e9a0ad94
    - type: entities
      show_header_toggle: false
      entities:
        - sensor.home_to_idx
        - sensor.home_to_bend
        - sensor.home_to_florence
        - sensor.home_to_portland
        - sensor.home_to_lincoln_city
    - type: entities
      title: Transport
      show_header_toggle: false
      entities:
        - entity: sensor.lyft_time
          name: Lyft Pickup Time
        - entity: sensor.lyft_xl_time
          name: Lyft XL Pickup Time
        - type: divider
        - entity: sensor.uberx_time
          name: Uber X Pickup Time
          icon: mdi:uber
        - entity: sensor.uberxl_time
          name: Uber XL Pickup Time
          icon: mdi:uber