- platform: broadlink
  host: '192.168.131.4'
  mac: 'b4:43:0d:f9:34:99'
  type: 'rm_mini'
  timeout: 30
  switches:
      bedroom_ir:
          friendly_name: "Bedroom IR"
          command_on: 'JgBgAAABJJUTEREUEBQTNxMRExIQFBEUEzYTERE5ExEROBM3EzYQORE4ERQQFBEUEDkRFBAUERQQFBE4EjYTNhIUETkQORA5EAAFOQABIk0RAAxBAAEiShIADEEAASFLEwANBQAAAAAAAAAA'
          command_off: 'JgBgAAABJJUTEREUEBQTNxMRExIQFBEUEzYTERE5ExEROBM3EzYQORE4ERQQFBEUEDkRFBAUERQQFBE4EjYTNhIUETkQORA5EAAFOQABIk0RAAxBAAEiShIADEEAASFLEwANBQAAAAAAAAAA'