# "The alpha_vantage sensor platform uses Alpha Vantage to monitor the stock market. This platform also provides detail about exchange rates."
# https://www.home-assistant.io/components/alpha_vantage/
- platform: alpha_vantage
  api_key: JTS874GEKEN01R7K
  symbols:
  - symbol: MAIN
    name: Main Street
  foreign_exchange:
  - from: BTC
    to: USD
    name: Bitcoin