# Weather Prediction
- platform: darksky
  api_key: !secret forcastio_api
  scan_interval:
    minutes: 10
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - cloud_cover
    - humidity
    - visibility
    - temperature_high
    - temperature_low
    - minutely_summary
    - hourly_summary
    - daily_summary

# US Weather Service Emergency Data
# https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853
- platform: rest
  resource: https://api.weather.gov/alerts/active/count
  name: NWS Alert Count
  value_template: >
    {% if value_json.zones.ORZ604 is defined %}
      {{ value_json.zones.ORZ604 }}
    {% elif value_json.zones.ORC039 is defined %}
      {{ value_json.zones.ORC039 }}
    {% else %}
      0
    {% endif %}
  headers:
    User-Agent: Homeassistant
    Accept: application/ld+json
  scan_interval: 300
    
- platform: rest
  resource: https://api.weather.gov/alerts/active?zone=ORZ604,ORC039
  name: NWS Alert Event
  value_template: >
    {% if value_json.features[0] is defined %}
      {{ value_json['features'][0]['properties'].event }}
    {% else %}
      None
    {% endif %}
  json_attributes:
    - features
  headers:
    User-Agent: Homeassistant
    Accept: application/geo+json
  scan_interval: 300

  # Air Quality
- platform: waqi
  token: 4c430aede0b393e4baa425b9ca43dd5c9afa29df
  locations:
    - eugene