- platform: template
  sensors:
    # Converting units
    convert_backyard_wind:
      entity_id: sensor.netatmo_backyard_strength
      unit_of_measurement: "mph"
      friendly_name: 'Backyard Wind Strength'
      value_template: "{{ (states('sensor.netatmo_backyard_strength') | float / 1.609) | round(2) }}"
    convert_backyard_gust:
      entity_id: sensor.netatmo_backyard_gust_strength
      unit_of_measurement: "mph"
      friendly_name: 'Backyard Wind Gust Strenth'
      value_template: "{{ (states('sensor.netatmo_backyard_gust_strength') | float / 1.609) | round(2) }}"
    # It will simplify cards and scripts to translate the current Harmony activity into the device and IDs in use
    living_room_media_activity_id:
      entity_id: remote.living_room
      value_template: >
        {% if states.remote.living_room.attributes.current_activity == "Watch Amazon" %}
          31480109
        {% elif states.remote.living_room.attributes.current_activity == "Watch Hulu" %}
          31949557
        {% elif states.remote.living_room.attributes.current_activity == "Watch Kodi" %}
          31479535
        {% elif states.remote.living_room.attributes.current_activity == "Watch Netflix" %}
          31478989
        {% elif states.remote.living_room.attributes.current_activity == "Watch OTA" %}
          31480260
        {% elif states.remote.living_room.attributes.current_activity == "Watch Plex" %}
          31571897
        {% elif states.remote.living_room.attributes.current_activity == "Watch Sling" %}
          31480008
        {% elif states.remote.living_room.attributes.current_activity == "Youtube" %}
          33323580
        {% elif states.remote.living_room.attributes.current_activity == "Listen to Music" %}
          38156985
        {% elif states.remote.living_room.attributes.current_activity == "Play Switch" %}
          31480190
        {% else %}
          unknown
        {% endif %}
      friendly_name: 'Current Activity ID' 
    living_room_media_device:
      entity_id: remote.living_room
      value_template: >
        {% if states.remote.living_room.attributes.current_activity == "Watch Kodi" %}
          htpc
        {% elif states.remote.living_room.attributes.current_activity == "Watch Amazon"
              or  states.remote.living_room.attributes.current_activity == "Watch Hulu"
              or  states.remote.living_room.attributes.current_activity == "Watch Netflix"
              or states.remote.living_room.attributes.current_activity == "Watch Plex"
              or states.remote.living_room.attributes.current_activity == "Watch Sling"
              or states.remote.living_room.attributes.current_activity == "Youtube" %}
          roku
        {% elif states.remote.living_room.attributes.current_activity == "Watch OTA" %}
          ota
        {% elif states.remote.living_room.attributes.current_activity == "Play Switch" %}
          switch
        {% elif states.remote.living_room.attributes.current_activity == "Listen to Music" %}
          bluetooth
        {% else %}
          unknown
        {% endif %}
      friendly_name: 'Current Remote Device:'
    living_room_media_device_id:
      entity_id: sensor.living_room_media_device
      value_template: >
        {% if is_state("sensor.living_room_media_device", "htpc") %}
          51738178
        {% elif is_state("sensor.living_room_media_device", "roku") %}
          51736885
        {% else %}
          off
        {% endif %}
      friendly_name: 'Current Media Device ID'
    # Harmony current activity
    living_room_remote_state:
      entity_id: remote.living_room
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'
      friendly_name: 'Current Activity:'
    # Attribute -> state
    outdoor_pressure:
      entity_id:  sensor.waqi_eugene_highway_99_oregon_usa
      value_template: '{{ states.sensor.waqi_eugene_highway_99_oregon_usa.attributes.pressure }}'
      friendly_name: 'Outdoor Pressure'
      unit_of_measurement: mbar
    # Money Math
    bitcoin_current_value:
      entity_id: 
       - sensor.exchange_rate_1_btc
       - input_number.bitcoin_quantity
      value_template: '{{ (states("sensor.exchange_rate_1_btc") | float * states("input_number.bitcoin_quantity") | float) | round(2) }}'
      friendly_name: BTC Position
      unit_of_measurement: USD
    combined_current_value:
      entity_id:
      - sensor.main_street_current_value
      - sensor.bitcoin_current_value
      value_template: '{{ (states("sensor.bitcoin_current_value") | float + states("sensor.main_street_current_value") | float) | round(2) }}'
      friendly_name: Total Postion
      unit_of_measurement: USD
    main_street_current_value:
      entity_id:
      - sensor.main_street
      - input_number.main_street_shared_owned
      value_template: '{{ (states("sensor.main_street") | float * states("input_number.main_street_shared_owned") | float) | round(2) }}'
      friendly_name: MAIN Postion
      unit_of_measurement: USD
    p_and_l:
      entity_id:
      - sensor.main_street
      - input_number.main_street_shared_owned
      - input_number.main_street_average_cost
      - sensor.exchange_rate_1_btc
      - input_number.bitcoin_quantity
      - input_number.bitcoin_average_cost
      value_template: '{{ ((states("sensor.main_street") | float * states("input_number.main_street_shared_owned") | float) - (states("input_number.main_street_average_cost") | float * states("input_number.main_street_shared_owned") | float) + (states("sensor.exchange_rate_1_btc") | float * states("input_number.bitcoin_quantity") | float) - (states("input_number.bitcoin_average_cost") | float * states("input_number.bitcoin_quantity") | float)) | round(2) }}'
      friendly_name: P&L
      unit_of_measurement: USD
    # Simple bool for decided if the house is empty of residents
    unoccupied_mode:
      entity_id:
        - device_tracker.tile_a8b3ea596f9b44fd
        - device_tracker.tile_4c66b3d3606d440e
        - input_boolean.force_away_mode
      friendly_name: 'Unoccuped Mode'
      value_template: >
        {% if is_state("input_boolean.force_away_mode", "on") %}
          on
        {% elif is_state("device_tracker.tile_a8b3ea596f9b44fd", "home")
          or is_state("device_tracker.tile_4c66b3d3606d440e", "home") %}
          off
        {% else %}
          on
        {% endif %}
    # Home Assistant Updates Available
    update_available:
      friendly_name: "An update is available"
      entity_id: updater.updater
      value_template: >-
        {% if state_attr('updater.updater', 'friendly_name') and (states.updater.updater != states.sensor.current_version) %}
          on
        {% else %}
          off
        {% endif %}
    # Utility Sensors
    utility_dow:
      entity_id: sensor.date
      friendly_name: 'Day Of The Week'
      value_template: >
        {{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}
    # WAQI States
    waqi_state:
      entity_id: sensor.waqi_eugene_wilkes_drive_oregon_usa
      friendly_name: Air Quality
      value_template: >
        {% if states('sensor.waqi_eugene_wilkes_drive_oregon_usa') | int < 51 %}
          good
        {% elif states('sensor.waqi_eugene_wilkes_drive_oregon_usa') | int < 101 %}
          moderate
        {% elif states('sensor.waqi_eugene_wilkes_drive_oregon_usa') | int < 151 %}
          unhealthy-1
        {% elif states('sensor.waqi_eugene_wilkes_drive_oregon_usa') | int < 201 %}
          unhealthy-2
        {% elif states('sensor.waqi_eugene_wilkes_drive_oregon_usa') | int < 300 %}
          unhealthy-3
        {% elif states('sensor.waqi_eugene_wilkes_drive_oregon_usa') | int > 300 %}
          hazardous
        {% else %}
          unknown
        {% endif %}