# Travel Times
- platform: waze_travel_time
  name: Home to IDX
  origin: zone.home
  destination: zone.idx
  region: 'US'
- platform: waze_travel_time
  name: Home to Bend
  origin: zone.home
  destination: zone.bend
  region: 'US'
- platform: waze_travel_time
  name: Home to Florence
  origin: zone.home
  destination: zone.florence
  region: 'US'
- platform: waze_travel_time
  name: Home to Portland
  origin: zone.home
  destination: zone.portland
  region: 'US'
- platform: waze_travel_time
  name: Home to Lincoln City
  origin: zone.home
  destination: zone.lincoln_city
  region: 'US'