esphome:
  name: hack1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "Jotunheim"
  password: "picklebutt"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hack1 Fallback Hotspot"
    password: "vuPJg2cEF55f"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "picklebutt"

ota:
  password: "picklebutt"
